Linear_Regression.ipynb ValueError: zero-size array to reduction operation maximum which has no identity
Probabilistic_Linear_Ensembles.ipynb

ValueError: cannot reshape array of size 0 into shape (0,newaxis)